apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: aspnetcore-hw
  labels:
    app: aspnetcore-hw
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aspnetcore-hw
  template:
    metadata:
      labels:
        app: aspnetcore-hw
    spec:
      containers:
        - name: api
          image: aspnetcore-from-compose
          ports:
            - containerPort: 80